### ISSUE TITLE
BUG report : TypeError: unhashable type 'slice'  , orz plz

### ISSUE THREAD

**Issue by bambooboy** [IBM/Autozoom-Attack#19]
How to fix this error , help ~ , cifar10 zoo_ae attack,plz 

Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main(args)
  File "main.py", line 117, in main
    codec.load_codec("D:\code\Autozoom-Attack-master\codec/cifar10_2")
  File "D:\code\Autozoom-Attack-master\setup_codec.py", line 142, in load_codec
    config2 = config[1::]
TypeError: unhashable type: 'slice'

**Comment by bambooboy** [comment]
plz

**Comment by bambooboy** [comment]
plz

**Comment by pinyuchen** [comment]
Hi @bambooboy  What Tensorflow version are you using? Can you try using TF 1.6?

**Comment by bambooboy** [comment]
thank you @pinyuchen  i use the TF 1.13.2,  i can't use 1.6.0 because of cuda version,  so is it a version problem ?

**Comment by pinyuchen** [comment]
I believe so. We didn't test on later TF versions.

**Comment by bambooboy** [comment]
thanks the reply, i'll try something else; have a nice day;
